[package]
name = "actix-example"
version = "0.1.0"
edition = "2024"

[dependencies]
ephem-debugger-rs = { path = "../../../packages/debugger-rs", features = ["actix"] }
actix-web = "4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry"] }
